/** Auto-generated by scripts/generate-gallery-manifest.ts — do not edit by hand. */
export const galleryFallbackImages = [
  "/desktop-background/couple (1).png",
  "/mobile-background/couple (1).png",
  "/desktop-background/couple (2).png",
  "/mobile-background/couple (2).png",
  "/mobile-background/couple (3).png",
  "/mobile-background/couple (4).png",
  "/mobile-background/couple (5).png",
  "/mobile-background/couple (6).png",
  "/mobile-background/couple (7).png",
  "/mobile-background/couple (8).png",
  "/mobile-background/couple (9).png",
  "/mobile-background/couple (10).png",
  "/mobile-background/couple (11).png",
  "/mobile-background/couple (12).png",
  "/mobile-background/couple (13).png",
  "/mobile-background/couple (14).png"
] as const
