/**
 * Writes content/gallery-images.ts from public/desktop-background and
 * public/mobile-background. Run before build so production has a bundled
 * manifest when the serverless runtime cannot read public/ via fs.
 *
 *   pnpm gallery:manifest
 */

import fs from "fs"
import path from "path"

const GALLERY_FOLDERS = ["desktop-background", "mobile-background"] as const
const GALLERY_IMAGE_PATTERN = /\.(webp|png|jpe?g)$/i
const OUT_FILE = path.resolve(process.cwd(), "content/gallery-images.ts")

function sortByNumericSuffix(paths: string[]): string[] {
  return [...paths].sort((a, b) => {
    const numA = parseInt(a.match(/\((\d+)\)/)?.[1] || "0", 10)
    const numB = parseInt(b.match(/\((\d+)\)/)?.[1] || "0", 10)
    return numA - numB
  })
}

function collectGalleryPaths(): string[] {
  const images: string[] = []

  for (const folder of GALLERY_FOLDERS) {
    const dir = path.join(process.cwd(), "public", folder)
    if (!fs.existsSync(dir)) continue

    const files = fs
      .readdirSync(dir)
      .filter((file) => GALLERY_IMAGE_PATTERN.test(file))
      .map((file) => `/${folder}/${file}`)

    images.push(...files)
  }

  return sortByNumericSuffix(images)
}

const images = collectGalleryPaths()

const content = `/** Auto-generated by scripts/generate-gallery-manifest.ts — do not edit by hand. */
export const galleryFallbackImages = ${JSON.stringify(images, null, 2)} as const
`

fs.writeFileSync(OUT_FILE, content, "utf8")
console.log(`Wrote ${images.length} gallery paths to ${path.relative(process.cwd(), OUT_FILE)}`)
